### ISSUE TITLE
Three.ts中有一个写死的ip导致本地部署的时候拉不到模型

### ISSUE THREAD

**Issue by CatInRl** [fengtianxi001/THREE-TurbineMonitor#2]
./src/utils/Three.ts:    
`const url = `http://192.168.3.45:3000/model/${src}`;`

**Comment by fengtianxi001** [comment]
嗯嗯嗯 改好了现在

**Comment by CatInRl** [comment]
好的 冯主任~
我是帮同事做的调研，代码很有用~
看了commit，感觉这样改的话是不是只能本地访问啊~
我不会前端，不然就帮你改了~

**Comment by fengtianxi001** [comment]
Demo的情况应该是打包后整个项目扔到web服务器就可以了。如果想单独部署模型到其他静态资源服务器的话， 你需要把上面的`const url ` 改成模型文件夹的网络路径

**Comment by CatInRl** [comment]
好的 建议可以在readme里面提一下~
